apiVersion: v1
kind: Service
metadata:
  name: jupyter-svc
spec:
  type: NodePort
  selector:
    app: jupyter
  ports:
    - name: p1
      port: 80
      targetPort: 8888
      protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-notebook
  labels:
    app: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
        - name: notebook
          image: "docker.io/linskybing/jupyterlab:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8888
          resources:
            limits:
              nvidia.com/gpu: "1"
          env:
            - name: JUPYTER_TOKEN
              value: "1234"
          volumeMounts:
            - name: user-home
              mountPath: /workspace
      volumes:
        - name: user-home
          nfs:
            server: "{{nfsServer}}"
            path: /
