apiVersion: v1
kind: ConfigMap
metadata:
  name: localization-unity-env-config
data:
  ROS_DOMAIN_ID: "1"
  RMW_IMPLEMENTATION: "rmw_fastrtps_cpp"
  FASTRTPS_DEFAULT_PROFILES_FILE: "/etc/ros/fastdds.xml"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: fastdds-optimization-config
data:
  fastdds.xml: |
    <?xml version="1.0" encoding="UTF-8" ?>
    <profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
        <participant profile_name="shm_opt_profile" is_default_profile="true">
            <rtps>
                <userTransports>
                    <transport_id>shm_transport</transport_id>
                    <type>SHM</type>
                </userTransports>
                <useBuiltinTransports>true</useBuiltinTransports>
            </rtps>
        </participant>
    </profiles>
    

---

apiVersion: v1
kind: Pod
metadata:
  name: ros2-localization-unity
  annotations:
    k8s.v1.cni.cncf.io/networks: "default/macvlan-conf"
  labels:
    app: "pros_app"
spec:
  containers:
  - name: rplidar
    image: "ghcr.io/screamlab/pros_jetson_driver_image:0.1.0"
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash","-c"]
    args:
      - |
        source /opt/ros/humble/setup.bash && \
        source /workspaces/install/setup.bash && \
        ros2 launch /workspace/pros_app/docker/compose/demo/rplidar_unity.xml
        
    envFrom:
      - configMapRef:
          name: localization-unity-env-config
    volumeMounts:
      - name: user-home
        mountPath: /workspace
      - name: shm
        mountPath: /dev/shm
      - name: dds-config
        mountPath: /etc/ros/fastdds.xml
        subPath: fastdds.xml
  - name: lidar-transform
    image: "ghcr.io/screamlab/pros_unity_lidar_trans_image:latest"
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash","-c"]
    args:
      - |
        source /opt/ros/humble/setup.bash && \
        source /workspaces/install/setup.bash && \
        ros2 run unity_lidar_transformer lidar_transformer_node
        
    envFrom:
      - configMapRef:
          name: localization-unity-env-config
    volumeMounts:
      - name: user-home
        mountPath: /workspace
      - name: shm
        mountPath: /dev/shm
      - name: dds-config
        mountPath: /etc/ros/fastdds.xml
        subPath: fastdds.xml
  - name: localization
    image: "ghcr.io/screamlab/pros_jetson_driver_image:0.1.0"
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash","-c"]
    args:
      - |
        source /opt/ros/humble/setup.bash && \
        source /workspaces/install/setup.bash && \
        ros2 launch /workspace/pros_app/docker/compose/demo/localization_unity.xml
        
    envFrom:
      - configMapRef:
          name: localization-unity-env-config
    volumeMounts:
      - name: user-home
        mountPath: /workspace
      - name: shm
        mountPath: /dev/shm
      - name: dds-config
        mountPath: /etc/ros/fastdds.xml
        subPath: fastdds.xml
  - name: rosbridge
    image: "ghcr.io/screamlab/pros_jetson_driver_image:0.1.0"
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash","-c"]
    args:
      - |
        source /opt/ros/humble/setup.bash && \
        source /workspaces/install/setup.bash && \
        ros2 launch rosbridge_server rosbridge_websocket_launch.xml \
        send_buffer_limit:=20000000 \
        fragment_timeout:=600
        
    ports:
      - containerPort: 9090
    envFrom:
      - configMapRef:
          name: localization-unity-env-config
    volumeMounts:
      - name: user-home
        mountPath: /workspace
      - name: shm
        mountPath: /dev/shm
      - name: dds-config
        mountPath: /etc/ros/fastdds.xml
        subPath: fastdds.xml
  - name: navigation
    image: "ghcr.io/screamlab/pros_jetson_driver_image:0.1.0"
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash","-c"]
    args:
      - |
        source /opt/ros/humble/setup.bash && \
        source /workspaces/install/setup.bash && \
        sleep 5 && \
        ros2 launch /workspace/pros_app/docker/compose/demo/navigation_unity.xml
        
    envFrom:
      - configMapRef:
          name: localization-unity-env-config
    volumeMounts:
      - name: user-home
        mountPath: /workspace
      - name: shm
        mountPath: /dev/shm
      - name: dds-config
        mountPath: /etc/ros/fastdds.xml
        subPath: fastdds.xml
  volumes:
    - name: user-home
      persistentVolumeClaim:
        claimName: "{{userVolume}}"
    - name: shm
      emptyDir:
        medium: Memory
        sizeLimit: 1Gi
    - name: dds-config
      configMap:
        name: fastdds-optimization-config
