apiVersion: batch/v1
kind: Job
metadata:
  name: map-saver-job
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: map-saver-job
      annotations:
        k8s.v1.cni.cncf.io/networks: "default/macvlan-conf"
    spec:
      restartPolicy: OnFailure
      containers:
      - name: map-saver
        image: "ghcr.io/screamlab/pros_jetson_driver_image:0.1.0"
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash","-c"]
        args:
          - |
            source /opt/ros/humble/setup.bash && \
            source /workspaces/install/setup.bash && \
            ros2 run nav2_map_server map_saver_cli -f /map/map01 --ros-args -p save_map_timeout:=10.0
            
        envFrom:
          - configMapRef:
              name: map-saver-env
        volumeMounts:
          - name: user-home
            mountPath: /map
            subPath: pros_app/docker/compose/demo/map/map01
      volumes:
        - name: user-home
          persistentVolumeClaim:
            claimName: "{{userVolume}}"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: map-saver-env
data:
  ROS_DOMAIN_ID: "1"
  RMW_IMPLEMENTATION: "rmw_fastrtps_cpp"
  ROS_LOCALHOST_ONLY: "0"
