apiVersion: v1
kind: Pod
metadata:
  name: ros2-yolo
  annotations:
    k8s.v1.cni.cncf.io/networks: "default/macvlan-conf"
  labels:
    app: "ros2_yolo"
spec:
  containers:
  - name: pros-cameraapi
    image: "registry.screamtrumpet.csie.ncku.edu.tw/screamlab/ros2_yolo_opencv_image:latest"
    imagePullPolicy: IfNotPresent
    command: ["/bin/bash","-c","--"]
    args: ["trap : TERM INT; sleep infinity & wait"]
    resources:
      requests:
        memory: "256Mi"
      limits:
        nvidia.com/gpu: "1"
    envFrom:
      - configMapRef:
          name: yolo-env
    volumeMounts:
      - name: user-home
        mountPath: /workspace/src
        subPath: ros2_yolo_integration/src
      - name: user-home
        mountPath: /workspace/screenshots
        subPath: ros2_yolo_integration/screenshots
      - name: user-home
        mountPath: /workspace/fps_screenshots
        subPath: ros2_yolo_integration/fps_screenshots
  volumes:
    - name: user-home
      persistentVolumeClaim:
        claimName: "{{userVolume}}"

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: yolo-env
data:
  ROS_DOMAIN_ID: "1"
  RMW_IMPLEMENTATION: "rmw_fastrtps_cpp"
