apiVersion: v1
kind: Pod
metadata:
  name: ros2-yolo
  annotations:
    k8s.v1.cni.cncf.io/networks: "default/macvlan-conf"
  labels:
    app: ros2_yolo
spec:
  containers:
    - name: pros-cameraapi
      image: "pros_cameraapi:latest"
      imagePullPolicy: IfNotPresent
      command: ["/bin/bash","-c","--"]
      args: ["trap : TERM INT; sleep infinity & wait"]
      resources:
        requests:
          memory: "256Mi"
        limits:
          nvidia.com/gpu: "1"
      envFrom:
        - configMapRef:
            name: yolo-env
      volumeMounts:
        - name: user-home
          mountPath: /workspace/src
          subPath: jpack5_yolo_opencv_image/src
        - name: user-home
          mountPath: /workspace/screenshots
          subPath: jpack5_yolo_opencv_image/screenshots
        - name: user-home
          mountPath: /workspace/fps_screenshots
          subPath: jpack5_yolo_opencv_image/fps_screenshots
        - name: user-home
          mountPath: /workspace/fastdds_net1.xml
          subPath: fastdds_net1.xml
  volumes:
    - name: user-home
      nfs:
        server: "{{nfsServer}}"
        path: /

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: yolo-env
data:
  ROS_DOMAIN_ID: "1"
  RMW_IMPLEMENTATION: "rmw_fastrtps_cpp"
  FASTRTPS_DEFAULT_PROFILES_FILE: "/workspace/fastdds_net1.xml"
